### ISSUE TITLE
[1.20.4] Fabric server throw the exeption.

### ISSUE THREAD

**Issue by Fantomrat** [lukebemish/excavated_variants#188]
```
java.nio.file.InvalidPathException: Illegal char <:> at index 31: .\world\data\excavated_variants:ore_replacement.dat
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.io.File.toPath(File.java:2387)
	at net.minecraft.class_18.method_17919(class_18.java:45)
	at net.minecraft.class_26.method_32384(class_26.java:122)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at net.minecraft.class_26.method_125(class_26.java:120)
	at net.minecraft.class_3218.method_14188(class_3218.java:824)
	at net.minecraft.class_3218.method_14176(class_3218.java:806)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:542)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:566)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

[crash-2024-01-12_20.14.13-server.txt](https://github.com/lukebemishprojects/ExcavatedVariants/files/13919490/crash-2024-01-12_20.14.13-server.txt)

**Comment by lukebemish** [comment]
Gotta love a good old platform-specific crash (this is a windows only issue, and I don't test on windows... at any rate, it's been fixed and I'll release a version with the fix shortly)
