### ISSUE TITLE
Not working on quilt server

### ISSUE THREAD

**Issue by Feliks-WR** [lukebemish/excavated_variants#201]
It displays some weird error message.

**Comment by lukebemish** [comment]
You need to provide the error message and both a client and server log or there's quite literally nothing I can do to help you troubleshoot

**Comment by Soulfate24** [comment]
Hi,
in "quilt.mod.json",

- missing information in "quilt_loader":
--  "group":

- error in "quilt_loader" > "depends":
-- "id": "defaultresources" < not found

Thank you ;)

**Comment by lukebemish** [comment]
While I appreciate that, that is still not a log. What version are you seeing this on?

**Comment by Soulfate24** [comment]
**I'm sorry about having no log, I'm testing a lot of mods (I'm on the 631st today) right now on Quilt 1.20.4 so I'm on a rush:**
```
---- Quilt Loader: Failed to load ----
Date/Time: 2024/05/10 22:58:24.1989
Quilt Loader Version: 0.26.0-beta.1

-- Error 1 --

Invalid 'quilt.mod.json' metadata file:<mods>/excavatedvariants-fabriquilt-1.20.4-4.1.3.jar!/quilt.mod.json

org.quiltmc.json5.exception.ParseException:  at line 3 column 20 path $.quilt_loader group is a required field

	at org.quiltmc.loader.impl.metadata.qmj.ModMetadataReader.parseException(ModMetadataReader.java:126)

	at org.quiltmc.loader.impl.metadata.qmj.V1ModMetadataReader.requiredString(V1ModMetadataReader.java:433)

	at org.quiltmc.loader.impl.metadata.qmj.V1ModMetadataReader.readFields(V1ModMetadataReader.java:155)

	at org.quiltmc.loader.impl.metadata.qmj.V1ModMetadataReader.read(V1ModMetadataReader.java:85)

	at org.quiltmc.loader.impl.metadata.qmj.ModMetadataReader.read(ModMetadataReader.java:105)

	at org.quiltmc.loader.impl.metadata.qmj.ModMetadataReader.read(ModMetadataReader.java:53)

	at org.quiltmc.loader.impl.plugin.quilt.StandardQuiltPlugin.scan0(StandardQuiltPlugin.java:288)

	at org.quiltmc.loader.impl.plugin.quilt.StandardQuiltPlugin.scanZip(StandardQuiltPlugin.java:271)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanZipWithPlugin(QuiltPluginManagerImpl.java:2175)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanZip(QuiltPluginManagerImpl.java:2151)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFile0(QuiltPluginManagerImpl.java:2077)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFile(QuiltPluginManagerImpl.java:2024)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl$1.visitFile(QuiltPluginManagerImpl.java:1935)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl$1.visitFile(QuiltPluginManagerImpl.java:1813)

	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFolder0(QuiltPluginManagerImpl.java:1813)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.scanModFolder(QuiltPluginManagerImpl.java:1794)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.addModFolder(QuiltPluginManagerImpl.java:1778)

	at org.quiltmc.loader.impl.plugin.BasePluginContext.addFolderToScan(BasePluginContext.java:86)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.runInternal(QuiltPluginManagerImpl.java:1242)

	at org.quiltmc.loader.impl.plugin.QuiltPluginManagerImpl.run(QuiltPluginManagerImpl.java:754)

	at org.quiltmc.loader.impl.QuiltLoaderImpl.runPlugins(QuiltLoaderImpl.java:598)

	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:315)

	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:307)

	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:149)

	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)

	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

-- Error 2 --

Excavated Variants requires version [3.3.3, ∞) of defaultresources, which is missing!

- <mods>/excavatedvariants-fabriquilt-1.20.4-4.1.3.jar

-- Plugin State --

Cycle number = 1
Cycle Step = START

Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)
```

**So I've edited json to add "group" and change "defaultresource" to "optional" for a more detailed log:**
```
Time: 2024-05-10 23:05:05
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'excavated_variants'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.util.ServiceConfigurationError: dev.lukebemish.excavatedvariants.api.RegistrationListener: Provider dev.lukebemish.excavatedvariants.impl.DefaultRegistrationListener could not be instantiated
	at java.base/java.util.ServiceLoader.fail(Unknown Source)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(Unknown Source)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.Spliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at dev.lukebemish.excavatedvariants.impl.platform.Services.loadListeners(Services.java:31)
	at dev.lukebemish.excavatedvariants.impl.RegistriesImpl.<clinit>(RegistriesImpl.java:51)
	at dev.lukebemish.excavatedvariants.impl.ExcavatedVariants.init(ExcavatedVariants.java:121)
	at dev.lukebemish.excavatedvariants.impl.fabriquilt.ExcavatedVariantsFabriQuilt.onInitialize(ExcavatedVariantsFabriQuilt.java:31)
	at dev.lukebemish.excavatedvariants.impl.fabriquilt.fabric.ExcavatedVariantsFabric.onInitialize(ExcavatedVariantsFabric.java:14)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:55)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: dev/lukebemish/defaultresources/api/GlobalResourceManager
	at dev.lukebemish.excavatedvariants.impl.DefaultRegistrationListener.<clinit>(DefaultRegistrationListener.java:56)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	... 30 more
Caused by: java.lang.ClassNotFoundException: dev.lukebemish.defaultresources.api.GlobalResourceManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:202)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:174)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:55)
	at net.minecraft.class_310.<init>(class_310.java:487)
Mixins in Stacktrace:
	net.minecraft.class_310:
		obro1961.chatpatches.mixin.MinecraftClientMixin (#chatpatches:chatpatches.mixins.json)
		smsk.smoothscroll.mixin.CreativeScreen.MinecraftClientMixin (#smoothscroll:smoothscroll.mixins.json)
		me.cortex.nvidium.mixin.minecraft.MixinMinecraftClient (#nvidium:nvidium.mixins.json)
		org.anti_ad.mc.ipnext.mixin.MixinMinecraftClient (#inventoryprofilesnext:mixins.ipnext.json)
		ru.kelcuprum.alinlib.mixin.events.client.MinecraftMixin (#alinlib:alinlib.mixin.json)
		opekope2.optigui.mixin.MinecraftClientMixin (#optigui:optigui.mixins.json)
		walksy.shield.mixin.MinecraftClientMixin (#completedshieldfix:shieldfixes.mixins.json)
		dev.emi.emi.mixin.MinecraftClientMixin (#emi:emi.mixins.json)
		ca.fxco.moreculling.mixin.MinecraftClient_managersMixin (#moreculling:moreculling.mixins.json)
		dev.nyon.bbm.asm.MinecraftMixin (#better-boat-movement:bbm.mixins.json)
		net.combatroll.mixin.MinecraftClientMixin (#combatroll:combatroll.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientAccessor (#bettercombat:bettercombat.mixins.json)
		dev.isxander.zoomify.mixins.hooks.MinecraftClientMixin (#zoomify:zoomify.mixins.json)
		com.anthonyhilyard.prism.mixin.MinecraftMixin (#prism:prism.mixins.json)
		dev.chachy.lazylanguageloader.client.mixin.optimizations.splash.MixinMinecraftClient (#lazy-language-loader:lazy-language-loader.mixin.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftMixin (#modernfix:modernfix-common.mixins.json)
		com.minenash.seamless_loading_screen.mixin.MinecraftClientMixin (#seamless_loading_screen:seamless_loading_screen-common.mixins.json)
		dev.isxander.controlify.mixins.feature.input.MinecraftMixin (#controlify:controlify.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (#ferritecore:ferritecore.fabric.mixin.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (#yet_another_config_lib_v3:yacl.mixins.json)
		com.yungnickyoung.minecraft.travelerstitles.mixin.MinecraftClientTickMixin (#travelerstitles:travelerstitles.mixins.json)
		dev.isxander.controlify.mixins.feature.rumble.MinecraftMixin (#controlify:controlify.mixins.json)
		org.quiltmc.qsl.screen.mixin.client.MinecraftClientMixin (#quilt_screen:quilt_screen.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (#lambdynlights:lambdynlights.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (#quilted_fabric_events_interaction_v0:quilted_fabric_events_interaction_v0.client.mixins.json)
		dev.lukebemish.dynamicassetgenerator.impl.mixin.MinecraftMixin (#dynamic_asset_generator:mixin.dynamic_asset_generator.json)
		dev.imb11.flow.mixin.MinecraftClientMixin (#flow:flow.mixins.json)
		org.betterx.betternether.mixin.client.MinecraftClientMixin (#betternether:betternether.mixins.client.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (#entity_texture_features:entity_texture_features-common.mixins.json)
		me.axieum.mcmod.authme.mixin.MinecraftClientAccessor (#authme:authme.mixins.json)
		dev.isxander.controlify.mixins.feature.screenop.MinecraftMixin (#controlify:controlify.mixins.json)
		tschipp.carryon.mixin.MinecraftMixin (#carryon:carryon.mixins.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (#voicechat:voicechat.mixins.json)
		me.cominixo.betterf3.mixin.ClientAccessor (#betterf3:betterf3.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftMixin (#collective:collective_fabric.mixins.json)
		traben.solid_mobs.mixin.MixinMinecraftClient (#solid_mobs:solid_mobs-common.mixins.json)
		net.anvian.glow_ink_plus.mixin.MixinMinecraft (#glow_ink_plus:glow_ink_plus.mixins.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (#nochatreports:mixins/fabric/nochatreports-fabric.mixins.json)
		tech.thatgravyboat.craftify.mixin.MinecraftClientMixin (#craftify:mixins.craftify.json)
		de.dafuqs.paginatedadvancements.mixin.MinecraftClientMixin (#paginatedadvancements:paginatedadvancements.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientMixin (#fastquit:fastquit.mixins.json)
		org.quiltmc.qsl.base.mixin.client.MinecraftClientMixin (#quilt_base:quilt_base.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (#quilted_fabric_registry_sync_v0:quilted_fabric_registry_sync_v0.client.mixins.json)
		bettercommandblockui.mixin.MinecraftClientMixin (#bettercommandblockui:bettercommandblockui.mixins.json)
		io.socol.betterthirdperson.mixin.MinecraftClientMixin (#betterthirdperson:betterthirdperson.mixins.json)
		com.ishland.vmp.mixins.timesource.MixinMinecraftClient (#vmp:vmp.mixins.json)
		com.blamejared.ambientenvironment.mixin.MixinMinecraft (#ambientenvironment:ambientenvironment.fabric.mixins.json)
		net.wisecase2.stutterfix.mixin.client.MinecraftClientMixin (#stutterfix:stutterfix.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.Minecraft_screenshotMixin (#memoryleakfix:memoryleakfix.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (#sodium-extra:sodium-extra.mixins.json)
		glitchcore.mixin.client.MixinMinecraft (#glitchcore:glitchcore.mixins.json)
		fuzs.forgeconfigapiport.fabric.mixin.client.MinecraftMixin (#forgeconfigapiport:forgeconfigapiport.fabric.mixins.json)
		org.quiltmc.qsl.registry.mixin.client.MinecraftClientMixin (#quilt_registry:quilt_registry.mixins.json)
		dev.bernasss12.bebooks.mixin.MinecraftClientMixin (#bebooks:bebooks.mixins.json)
		org.betterx.betterend.mixin.client.MinecraftClientMixin (#betterend:betterend.mixins.client.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (#entity_texture_features:entity_texture_features-common.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (#sodium:sodium.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (#citresewn-defaults:citresewn-defaults.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc46766.MinecraftMixin (#debugify:debugify.client.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.feature.measure_time.MinecraftMixin_Fabric (#modernfix:modernfix-fabric.mixins.json)
		dev.lukebemish.excavatedvariants.impl.fabriquilt.mixin.ClientInitializerMixin (#excavated_variants:mixin.excavated_variants_fabriquilt.json)
		fabric.me.thosea.badoptimizations.mixin.fps_string.MixinClient (#badoptimizations:fabric-badoptimizations.mixins.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (#nochatreports:mixins/common/nochatreports.mixins.json)
		squeek.appleskin.mixin.MinecraftClientMixin (#appleskin:appleskin.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (#quilted_fabric_data_generation_api_v1:quilted_fabric_data_generation_api_v1.client.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.core.MCMixin_Fabric (#modernfix:modernfix-fabric.mixins.json)
		me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (#fabrishot:mixins.fabrishot.json)
		net.raphimc.immediatelyfast.injection.mixins.core.MixinMinecraftClient (#immediatelyfast:immediatelyfast-common.mixins.json)
		org.quiltmc.qsl.frozenblock.core.registry.mixin.client.MinecraftMixin (#frozenlib:mixin/frozenlib_quiltmc_registry.mixins.json)
		com.noxcrew.noxesium.mixin.component.ext.MinecraftExt (#noxesium:noxesium.mixins.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (#entity_model_features:entity_model_features-common.mixins.json)
		com.github.dimadencep.mods.rrls.mixins.MinecraftClientMixin (#rrls:rrls-common.mixins.json)
		com.natamus.simplemenu_common_fabric.mixin.MinecraftMixin (#simplemenu:simplemenu_fabric.mixins.json)
		org.quiltmc.qsl.lifecycle.mixin.client.MinecraftClientMixin (#quilt_lifecycle_events:quilt_lifecycle_events.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (#spruceui:spruceui.mixins.json)
		net.wisecase2.stutterfix.mixin.client.RemoveYieldMixin (#stutterfix:stutterfix.mixins.json)
		de.guntram.mcmod.easiercrafting.mixins.GuiInventoryMixin (#easiercrafting:mixins.easiercrafting.json)
		org.embeddedt.modernfix.common.mixin.feature.measure_time.MinecraftMixin (#modernfix:modernfix-common.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.world_leaks.MinecraftMixin (#modernfix:modernfix-common.mixins.json)
		ru.kelcuprum.ruthenium.mixin.MinecraftMixin (#ruthenium:ruthenium.mixin.json)
		org.quiltmc.qsl.resource.loader.mixin.client.MinecraftClientMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		dev.kir.cubeswithoutborders.mixin.MinecraftClientMixin (#cubes-without-borders:cubes-without-borders.mixins.json)
		com.natamus.globalnarrationtoggle_common_fabric.mixin.MinecraftMixin (#globalnarrationtoggle:globalnarrationtoggle_fabric.mixins.json)
		org.quiltmc.qsl.networking.mixin.accessor.MinecraftClientAccessor (#quilt_networking:quilt_networking.mixins.json)
		traben.entity_model_features.mixin.MixinResourceReload (#entity_model_features:entity_model_features-common.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientAccessor (#languagereload:languagereload.mixins.json)
		net.darkhax.bookshelf.mixin.accessors.client.AccessorMinecraft (#bookshelf:bookshelf.common.mixins.json)
		net.irisshaders.iris.mixin.MixinMinecraft_Images (#iris:mixins.iris.json)
		com.noxcrew.noxesium.mixin.performance.render.MinecraftMixin (#noxesium:noxesium.mixins.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (#iceberg:iceberg.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientAccessor (#fastquit:fastquit.mixins.json)
		com.flamearrows.mars.mixin.client.ExampleClientMixin (#flamearrows:flamearrows.client.mixins.json)
		de.guntram.mcmod.clickthrough.mixins.ItemUseMixin (#clickthrough:mixins.clickthrough.json)
		dynamic_fps.impl.mixin.MinecraftMixin (#dynamic_fps:dynamic_fps-common.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.concurrency.MinecraftMixin (#modernfix:modernfix-common.mixins.json)
		com.bettercrafting.mars.mixin.client.ExampleClientMixin (#bettercrafting:bettercrafting.client.mixins.json)
		io.github.cottonmc.cotton.gui.impl.mixin.client.MinecraftClientMixin (#libgui:mixins.libgui.json)
		dev.isxander.controlify.mixins.core.MinecraftMixin (#controlify:controlify.mixins.json)
		org.quiltmc.qsl.command.mixin.client.MinecraftClientMixin (#quilt_client_command:quilt_client_command.mixins.json)
		net.irisshaders.iris.mixin.MixinMinecraft_PipelineManagement (#iris:mixins.iris.json)
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (#tcdcommons:tcdcommons.client.mixin.events.json)
		dev.imb11.sounds.mixin.ui.ScreenSoundEffect (#sounds:sounds.mixins.json)
		joshie.gauntlets.mixin.client.MinecraftClientMixin (#gauntlets:gauntlets.client.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.blast_search_trees.MinecraftMixin (#modernfix:modernfix-common.mixins.json)
		dev.isxander.controlify.mixins.feature.virtualmouse.MinecraftMixin (#controlify:controlify.mixins.json)
		ca.fxco.moreculling.mixin.blockstates.MinecraftClient_loadBlocksMixin (#moreculling:moreculling.mixins.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (#controlling:controlling.fabric.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (#satin:mixins.satin.client.json)
		net.bettercombat.mixin.client.MinecraftClientInject (#bettercombat:bettercombat.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientMixin (#languagereload:languagereload.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (#balm-fabric:balm.fabric.mixins.json)
		net.irisshaders.iris.mixin.MixinMinecraft_Keybinds (#iris:mixins.iris.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (#architectury:architectury.mixins.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.Minecraft_targetClearMixin (#memoryleakfix:memoryleakfix.mixins.json)
		org.betterx.bclib.mixin.client.MinecraftMixin (#bclib:bclib.mixins.client.json)
```

**Comment by lukebemish** [comment]
1.20.4, cool, that's the info I needed... I'll get that fixed shortly.

**Comment by Soulfate24** [comment]
Thank you :) I wasn't mentally ready to play without Excavated Variants !

**Comment by lukebemish** [comment]
Resolved, in theory, in the new release
