### ISSUE TITLE
[1.20.1] Forge - Issue with textures

### ISSUE THREAD

**Issue by MrPYF** [lukebemish/excavated_variants#210]
Issues with Inferium/Prosperity (Mystical Agriculture) and Brilliant Stone (Malum) in Andesite/Granite/Diorite/Tuff not rendering properly in world or as an item.
Drops are good, just a texture issue.

![Blocks in world](https://github.com/lukebemishprojects/ExcavatedVariants/assets/174806784/da858773-dc00-4f7d-9942-b678369ab9d6)
![Items in inventory](https://github.com/lukebemishprojects/ExcavatedVariants/assets/174806784/726cdc1b-0f50-47e6-ba85-ece16a816c6b)

**Comment by MrPYF** [comment]
Hello,

Small update as I was working around my modpack again, it appears that Inferium/prosperity (Mystical Agriculture) and Brilliant Stone (Malum), actually have a texture issue with all those blocks :

- Diorite (vanilla)
- Andesite (vanilla)
- Granite (vanilla)
- Tuff (vanilla)
- Smooth Basalt (vanilla)
- Dripstone Block (vanilla)
- Sandstone (vanilla)
- Red Sandstone (vanilla)

- Shale (Quark)
- Jasper (Quark)
- Limestone (Quark)

- Scorchia (Create)
- Scoria (Create)
- Limestone (Create)
- Crimsite (Create)
- Calcite (Create)
- Asurine (Create)
- Ochrum (Create)
- Veridium (Create)

- White Sandstone (Biomes O' Plenty)
- Orange Sandstone (Biomes O' Plenty)

Haven't noticed any other ore than those 3 having an issue.
Hope it will help figuring out the issue.

Regard.


![2024-07-27_15 38 41](https://github.com/user-attachments/assets/4153d3ae-b274-455a-a9e0-cddb9ba96800)

**Comment by lukebemish** [comment]
Yep, okay. I think I know what's going on here -- I could swear I'd fixed this already but I guess not. I'm planning to release a new release for 1.20.1 in a week or so; it'll hopefully have a fix for this too.

**Comment by VictoriaSilver** [comment]
A quick workaround that I've found for the meantime is

1. Disable all mods except Dynamic Asset Generator, Excavated Variants, and [any of your mods which EV supports](https://github.com/lukebemishprojects/ExcavatedVariants/tree/1.20.1/Common/src/main/resources/defaultresources/excavated_variants/excavated_variants/variants)
2. Open `config/dynamic_asset_generator.json` and change both `cache_assets` and `cache_data` to `true`
3. Start the game, let it get to the title screen, close the game
4. Re-enable all of your mods

You'll need to repeat this if you add any other mods supported by EV, but that's all.

**Comment by TorchTheDragon** [comment]
Hate to bring this back up, but this also exists in NeoForge 1.21.1 
![image](https://github.com/user-attachments/assets/d3236017-0872-4cdb-b68c-d0441d7d11db)

**Comment by lukebemish** [comment]
Hmm. Just to confirm, the only mods needed to see this issue are Excavated Variants, Dynamic Asset Generator, and Malum or Mystical Agriculture?

**Comment by TorchTheDragon** [comment]
I can test that real quick with just those three mods (DAG, EV, and MA)

**Comment by TorchTheDragon** [comment]
Here are the mods installed in the test build 

![image](https://github.com/user-attachments/assets/7d888a14-13b5-49e8-859f-ecbd2e15882a)

Still Occurs

![image](https://github.com/user-attachments/assets/007ff133-55e6-4fb3-8cf6-1d546bb37ea3)

**Comment by lukebemish** [comment]
Thanks, I'll give it a poke; pretty sure I know what the issue is, just have to figure out why it broke again.

**Comment by ghost** [comment]
Running in to the same issue, did some testing.

Configuration 1: EV + DAG + Malum + Mystical Agriculture Results:
- error texture (magenta/black) blocks for all EV versions of Malum ores.
- stone texture only (missing ore overlay) for MA ores.

Configuration 2: EV + DAG + Mystical Agriculture Results:
- ~~Everything working normally~~
- I must have been mistaken about this, I think I saw one of the stock MA ores perhaps? No, MA is still broken.

Configuration 3: EV + DAG + Malum Results:
- error texture (magenta/black) blocks for all EV versions of Malum ores.

~~The "trigger" seems to be the Malum ores specifically, which I'm guessing might have something to do with the glow and/or animation frames they have. It's the only thing that stands out as different about them.~~

There's also _this_ funny little anomaly:
![image](https://github.com/user-attachments/assets/6106deed-fc1f-48eb-8d12-4a65bb6a7db4)

Somehow EV/DAG amalgamated 'mystical agriculture', 'soulstone' (from malum), and 'blazing quartz ore' (also from malum), into a single block? Very strange! :P

And, just in case it helps, here's one of the exceptions DAG spits out in relation to the broken textures:

```
[23:17:23] [Worker-Main-15/ERROR] [dynamic_asset_generator/]: Could not write image to stream for source {"sources":{"stoneNew0":{"source":{"path":"minecraft:block/sandstone_top","type":"dynamic_asset_generator:texture"}},"ore0":{"source":{"path":"minecraft:blank","type":"dynamic_asset_generator:texture"}},"ore1":{"source":{"path":"minecraft:blank","type":"dynamic_asset_generator:texture"}},"stoneOld0":{"source":{"path":"minecraft:block/stone","type":"dynamic_asset_generator:texture"}}},"generator":{"background":{"sources":[{"capture":"stoneOld0","type":"dynamic_asset_generator:frame_capture"}],"type":"dynamic_asset_generator:overlay"},"full":{"sources":[{"capture":"ore0","type":"dynamic_asset_generator:frame_capture"},{"capture":"ore1","type":"dynamic_asset_generator:frame_capture"}],"type":"dynamic_asset_generator:overlay"},"new_background":{"sources":[{"capture":"stoneNew0","type":"dynamic_asset_generator:frame_capture"}],"type":"dynamic_asset_generator:overlay"},"type":"dynamic_asset_generator:foreground_transfer"},"type":"dynamic_asset_generator:animation_splitter"}: excavated_variants:textures/block/sandstone_brilliant_stone_0_2.png
java.io.IOException: Issue loading texture: minecraft:blank
	at dev.lukebemish.dynamicassetgenerator.api.client.generators.texsources.TextureReaderSource.lambda$getSupplier$1(TextureReaderSource.java:56) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.impl.client.TexSourceCache.lambda$fromCache$1(TexSourceCache.java:47) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.impl.CacheReference.calcSync(CacheReference.java:16) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.impl.client.TexSourceCache.fromCache(TexSourceCache.java:44) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.impl.client.TexSourceCachingWrapper.lambda$getSupplier$2(TexSourceCachingWrapper.java:38) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.api.client.generators.texsources.AnimationSplittingSource.lambda$getSupplier$4(AnimationSplittingSource.java:69) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.impl.client.TexSourceCache.fromCache(TexSourceCache.java:37) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.impl.client.TexSourceCachingWrapper.lambda$getSupplier$2(TexSourceCachingWrapper.java:38) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.api.client.generators.TextureGenerator.lambda$get$3(TextureGenerator.java:52) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at dev.lukebemish.dynamicassetgenerator.api.ResourceCache.lambda$wrapSafeData$2(ResourceCache.java:127) ~[0_Library_DynamicAssetGenerator.jar%23162!/:4.2.2] {re:classloading}
	at net.minecraft.server.packs.resources.Resource.m_215507_(Resource.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading}
	at net.minecraft.client.renderer.texture.SpriteLoader.m_245083_(SpriteLoader.java:138) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.atlas.SpriteSource$Output.m_261059_(SpriteSource.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

```

I'll keep Malum out of my pack until this is resolved. Hope this helps! Thank you!

**Comment by lukebemish** [comment]
Hmm... That is a _weird_ error message. I bet one of the mods in question has changed how they handle models since I last had to poke this. I'll give it a poke. Thanks for the info!

**Comment by ghost** [comment]
Aaaand after turning on all of my other mods, Mystical Agriculture EV ores broke again. (Same way, base stone texture with no ore spots)

Gotta go to bed now but tomorrow I'll bisect my mod list and try to track down what's causing it. No exceptions in the logs for any of the MA ores, so no smoking guns to make it easy, unfortunately.

**Comment by ghost** [comment]
Ok, so, completely isolated MA+EV breaks in a brand new Forge47.3.0+mc1.20.1 instance. I must have been mistaken earlier about them working. It was late :P

**Comment by ghost** [comment]
One last thing, I went ahead and generated clean instance logs for you:

EV + MA:
[https://mclo.gs/FWsFPl5](https://mclo.gs/FWsFPl5)

EV + Malum:
[https://mclo.gs/J0EEcI1](https://mclo.gs/J0EEcI1)

**Comment by lukebemish** [comment]
Thanks! I'll poke it when I have the chance -- I have some ideas what's going on here I'll need to test

**Comment by Leichenengel** [comment]
Reporting in the same issue with NeoForge using EV and DAB (from the one mentioned above). I do have other Mod's that affect Terrain like Terralith, Oh The Biomes We've Gone (and it's dependencies) and Farmer's Delight and some of it's AddOns as well as Repurposed Structures and YUNG's Mods...well and a ton of Seriliums QoL-Mods.

![2024-11-29_22 45 14](https://github.com/user-attachments/assets/a1e218b9-999b-45d5-9022-2fe8c30ac036)

Using NeoForge on it's latest Version for 1.21.1 and of all mods mentioned the latest Versions for 1.21.1 on NeoForge/Forge and some spare ones only marked as 1.21 but got loaded in without issues.
For now I only found the Vanilla Granite Variant of your Mod to look like this but I assume that other Vanilla-Variants may be affected as well.
EDIT: Just fount a Dripstone Variant - Also broken texture replaced with that black-purple placeholder. This time it wasn't copper though but coal. I do use a resource pack (Alacrity 32x by Satellence). Shouldn't be the problem though (imho) :D

It's not game breaking for me. An aesthetic nuisance at best, but wanted to give you a head's up :)

Cheers

**Comment by Peach774** [comment]
I know its been a while but on 1.20.1, this doesn't seem to have been fixed yet. Anyone have something that works or is there any update?

**Comment by RealSpySap** [comment]
Also popping in nearly a year later to add that I'm also having this issue. Forge 1.20.1, Inferium & Prosperity [Mystical Agriculture] ores don't appear on any stone variants, modded or vanilla.
