### ISSUE TITLE
[BUG] after updating aydnamic asset gen and exc variants to 0.6.0

### ISSUE THREAD

**Issue by SDUBZ** [lukebemish/excavated_variants#43]
### What went wrong?

forge:1.18.2-40.1.19
mod versions 
excavated_variants-forge-1.18.2-0.6.0
dynamic_asset_generator-forge-1.18.2-0.6.0

both minecraft server and client refuse to load 
with the following error

SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/steven.WIN-I1LLGJ7KTA1.003/Forgagerserver/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
Exception in thread "main" java.lang.IllegalArgumentException: version: Version string does not start with a number
        at java.base/java.lang.module.ModuleDescriptor$Version.<init>(ModuleDescriptor.java:1005)
        at java.base/java.lang.module.ModuleDescriptor$Version.parse(ModuleDescriptor.java:1090)
        at java.base/java.lang.module.ModuleDescriptor$Builder.version(ModuleDescriptor.java:2062)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.16/net.minecraftforge.fml.loading.moddiscovery.ModJarMetadata.descriptor(ModJarMetadata.java:72)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:47)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder$JarModuleReference.<init>(JarModuleFinder.java:50)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder.lambda$new$0(JarModuleFinder.java:28)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder.<init>(JarModuleFinder.java:29)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.JarModuleFinder.of(JarModuleFinder.java:43)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

### Platform

Forge

### Version

1.18.2-40.1.19

**Comment by lukebemish** [comment]
Yes, this is a known issue. Fixed in forge 0.6.1, which is on Modrinth and will shortly be on Curseforge.

**Comment by lukebemish** [comment]
Not sure why Forge crashes if an improper version is supplied, but oh well.

**Comment by SDUBZ** [comment]
okay thank you
