### ISSUE TITLE
[BUG] Quark Compatibility

### ISSUE THREAD

**Issue by Bazyliii** [lukebemish/excavated_variants#45]
### What went wrong?

Game is crashing when Quark and Excavated Variants are present :/

Quark version: 3.2-356
Excavated Variants version: 0.6.1

I have deleted all configs and problem still occurs.

### Platform

Forge

### Version

0.6.1

### Logs and Screenshots

crash log:

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2022-05-15 14:59:47,838 main WARN Advanced terminal features are not available in this environment
[14:59:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, <ACCESS TOKEN>, --version, MultiMC5, --gameDir, E:/UltimMC/instances/Creatio/.minecraft, --assetsDir, E:/UltimMC/assets, --assetIndex, 1.18, --uuid, , --accessToken, ????????, --userType, Local, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.20, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width, 854, --height, 480]
[14:59:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.2 by Eclipse Adoptium
[14:59:48] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/UltimMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
[14:59:49] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[14:59:49] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, MultiMC5, --gameDir, E:\UltimMC\instances\Creatio\.minecraft, --assetsDir, E:\UltimMC\assets, --uuid, , --username, <ACCESS TOKEN>, --assetIndex, 1.18, --accessToken, ????????, --userType, Local, --versionType, release, --width, 854, --height, 480]
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Callback Metafactory Transformer]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 20 more
Caused by: java.lang.RuntimeException: java.util.ServiceConfigurationError: io.github.lukebemish.excavated_variants.ICreativeTabLoader: Provider io.github.lukebemish.excavated_variants.forge.CreativeTabLoaderImpl could not be instantiated
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.20/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:138)
	... 26 more
Caused by: java.util.ServiceConfigurationError: io.github.lukebemish.excavated_variants.ICreativeTabLoader: Provider io.github.lukebemish.excavated_variants.forge.CreativeTabLoaderImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1812)
	at TRANSFORMER/excavated_variants@0.6.1/io.github.lukebemish.excavated_variants.platform.Services.load(Services.java:18)
	at TRANSFORMER/excavated_variants@0.6.1/io.github.lukebemish.excavated_variants.platform.Services.<clinit>(Services.java:13)
	at TRANSFORMER/excavated_variants@0.6.1/io.github.lukebemish.excavated_variants.ExcavatedVariants.<clinit>(ExcavatedVariants.java:33)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration.localvar$zzh000$excavated_variants_oreConfigInit(OreConfiguration.java:526)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration.<init>(OreConfiguration.java)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.configurations.OreConfiguration.<init>(OreConfiguration.java:37)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.features.OreFeatures.<clinit>(OreFeatures.java:53)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.features.FeatureUtils.m_206469_(FeatureUtils.java:23)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:138)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.m_41720_(ItemStack.java:206)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.<init>(ItemStack.java:146)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.<init>(ItemStack.java:138)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.<init>(ItemStack.java:126)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.<clinit>(ItemStack.java:89)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.CreativeModeTab.<init>(CreativeModeTab.java:103)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.CreativeModeTab$1.<init>(CreativeModeTab.java:15)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.CreativeModeTab.<clinit>(CreativeModeTab.java:15)
	at TRANSFORMER/excavated_variants@0.6.1/io.github.lukebemish.excavated_variants.forge.CreativeTabLoaderImpl.setup(CreativeTabLoaderImpl.java:19)
	at TRANSFORMER/excavated_variants@0.6.1/io.github.lukebemish.excavated_variants.forge.CreativeTabLoaderImpl.<clinit>(CreativeTabLoaderImpl.java:15)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 22 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Optional.of(Optional.java:113)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.Items.handler$zbf000$overrideStackedOnOther(Items.java:1247)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.Items.m_151096_(Items.java:1122)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.Items.<clinit>(Items.java:622)
	... 38 more
Exiting with -1
Process exited with code -1.

**Comment by lukebemish** [comment]
Fixed in v0.6.2 by making service loading evaluate lazily.
